### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by ApfelUser** [snikch/csp#2]
^

**Comment by snikch** [comment]
Hrm, a victim of the Heroku free mode going away. I've upgraded the heroku plan to a paid one, but the app still doesn't seem to be accepting connections. Will give it a bit of time and hopefully it comes right.

**Comment by snikch** [comment]
Looks like the DNS settings were incorrect, the underlying IP changed. You can visit cspisawesome.herokuapp.com while the dns changes propogate.

**Comment by ApfelUser** [comment]
Thanks!

**Comment by anselmh** [comment]
It’s still down for me… any news?

**Comment by snikch** [comment]
Separate issue. Looks like Media Temple failed to renew the domain and decided it wasn't worth notifying me or anything. Awesome job :+1:. Waiting to hear back from their support, then I'll be moving it straight off to a different provider.

**Comment by snikch** [comment]
Fixed a day or two ago FYI.

**Comment by anselmh** [comment]
<3 Thanks!
